#!/bin/bash
# echobox, a script needed by ainstall, is a script that takes input and throws it out in an ascci box.
# Example:
# input: "Subscribe to the channel JR Tech & Software!"
# output: ------------------------------------------------
#         | Subscribe to the channel JR Tech & Software! |
#         ------------------------------------------------

# If we don't have an argument, ask for input from empty command line. Commented lines are for debugging.
# First add 4 to the chars variable we will use for the dashes>
if [[ ! $1 == "" ]]; then
	chars=$((${#1} + 4))
	#echo $chars
	# Use printf so that we don't have an automatic new line afterward
	for ((n=0;n<$chars;n++)); do printf "-" ;done
	printf "\n"
	printf "| $1 |\n"
	for ((n=0;n<$chars;n++)); do printf "-" ;done
	printf "\n"
	exit
fi

# If no argument, use read to get input
read message
chars=$((${#message} + 4))
#echo $chars
for ((n=0;n<$chars;n++)); do printf "-" ;done
printf "\n"
printf "| $message |\n"
for ((n=0;n<$chars;n++)); do printf "-" ;done
printf "\n"
