#!/bin/bash

# This script is under the MIT License.
# Copyright 2024 Jeremiah Haven
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation 
# files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, 
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to 
# do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE 
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# it explains itself. set this as your desktop manager's default mail client
# if you don't care to get an actual one.

/bin/echo "=== EMAIL READER ===" > /home/$USER/email
/bin/echo "" >> /home/$USER/email
/bin/echo "There are certain things on the system that are bent on calling" >> /home/$USER/email
/bin/echo "on your desktop's email client to do something. For me, it's seeing" >> /home/$USER/email
/bin/echo "log information. But what if we don't use a mail client? Well, here" >> /home/$USER/email
/bin/echo "is the solution! Displayed undernieth the equals signs below is" >> /home/$USER/email
/bin/echo "the exact string of information that the program tried to send to" >> /home/$USER/email
/bin/echo "a mail client. Enjoy!" >> /home/$USER/email
/bin/echo "" >> /home/$USER/email
/bin/echo "================" >> /home/$USER/email
/bin/echo "" >> /home/$USER/email
/bin/echo $1 >> /home/$USER/email
/usr/bin/pluma /home/$USER/email
