#!/bin/bash

# This script is under the MIT License.
# Copyright 2019 Jeremiah Haven
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation 
# files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, 
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to 
# do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE 
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# gen-iso DOES NOT WORK!!! It got overly bloated and I stopped working on it.

if [[ $1 == "" ]] 
then
	echo Cannot do anything without arguments. Try gen-iso --help for list
	echo of arguments
	exit
fi
if [[ $1 == "--help" ]] 
then
	echo gen-iso - the .iso creater
	echo 
	echo 
	echo "gen-iso's only argument is it's -s argument to specify the size"
	echo of the iso file. You can also use -n for a file name. The default
	echo 'is "image.iso".'
	exit
fi
if [[ $1 == "-s" ]] 
then
	if [[ $2 == "" ]] 
	then
		echo Must give a size in G for gigabytes and M for Megabytes.
		exit
	else
		if [[ $1 == "-n" ]] 
		then
			echo Can only use -n argument after -s argument.
			exit
		fi
		if [[ $3 == "-n" ]] 
		then
			if [[ $4 == "" ]] 
			then
				echo Must type in a name for the .iso file after
				echo -n argument.
				exit
			else
				fallocate -l $2 $4
				exit
			fi
		else
			fallocate -l $2 image.img
			exit
		fi
fi

exit
exit
