#!/usr/bin/python


# pvm is actually a python script that prints out to the screen the message "It's mv NOT vm!!!!!"!
# I used to be in a havvit of typing vm instead of mv so I wrote this script to remind myself that it
# is actually mv. This script will later be called on by a bash script

from time import sleep
import os

# Function written to make code look cleaner
def writeToScreen(message, time):
	os.system("clear")
	print(message)
	sleep(time)
	os.system("clear")
	
# Write the message
writeToScreen("Test", 0.01)
writeToScreen("m", 0.35)
writeToScreen("\nvm", 0.3)
writeToScreen("\n\n vm", 0.25)
writeToScreen("\n\n\nT vm", 0.2)
writeToScreen("\n\n\n\nOT vm", 0.15)
writeToScreen("\n\n\n\n\nNOT vm", 0.1)
writeToScreen("\n\n\n\n\n\n NOT vm", 0.05)
writeToScreen("\n\n\n\n\n\n\nv NOT vm", 0.1)
writeToScreen("\n\n\n\n\n\n\n\nmv NOT vm", 0.15)
writeToScreen("\n\n\n\n\n\n\n\n\n mv NOT vm", 0.2)
writeToScreen("\n\n\n\n\n\n\n\n\n\ns mv NOT vm", 0.25)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n's mv NOT vm", 0.3)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\nt's mv NOT vm", 0.35)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\nIt's mv NOT vm", 0.3)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n\n It's mv NOT vm!", 0.25)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n  It's mv NOT vm!!", 0.25)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n   It's mv NOT vm!!!", 0.25)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n     It's mv NOT vm!!!!", 0.25)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n      It's mv NOT vm!!!!!", 0.3)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n      It's mv NOT vm!!!!!!", 0.35)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n       It's mv NOT vm!!!!!!!", 0.4)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n\n        It's mv NOT vm!!!!!!!!", 0.45)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n         It's mv NOT vm!!!!!!!!!", 0.5)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n          It's mv NOT vm!!!!!!!!!!", 0.55)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n\n           It's mv NOT vm!!!!!!!!!!!", 0.6)
writeToScreen("\n\n\n\n\n\n\n\n\n\n\n\n            It's mv NOT vm!!!!!!!!!!!", 5)
exit
