#!/bin/bash

# This script is under the MIT License.
# Copyright 2019 Jeremiah Haven
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation 
# files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, 
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to 
# do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE 
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# redctl is a script that requires redshift to be installed. It uses the redshift command to give redshift
# a "leveled" interface of intensity from 1-7, then "off" to turn it off rather than using the default method
# of defining the intensity in the redshift command.

# Levels (Goes down by 5000 every time)
if [ $1 == "1" ]; then
	redshift -O 5000 >> /dev/null
fi
if [ $1 == "2" ]; then
        redshift -O 4500 >> /dev/null
fi
if [ $1 == "3" ]; then
        redshift -O 4000 >> /dev/null
fi
if [ $1 == "4" ]; then
        redshift -O 3500 >> /dev/null
fi
if [ $1 == "5" ]; then
        redshift -O 3000 >> /dev/null
fi
if [ $1 == "6" ]; then
        redshift -O 2500 >> /dev/null
fi
if [ $1 == "7" ]; then
        redshift -O 2000 >> /dev/null
fi
if [ $1 == "off" ]; then
	redshift -x >> /dev/null
fi
