#!/bin/bash
if [ $1 == "1" ]; then
	redshift -O 5000 >> /dev/null
fi
if [ $1 == "2" ]; then
        redshift -O 4500 >> /dev/null
fi
if [ $1 == "3" ]; then
        redshift -O 4000 >> /dev/null
fi
if [ $1 == "4" ]; then
        redshift -O 3500 >> /dev/null
fi
if [ $1 == "5" ]; then
        redshift -O 3000 >> /dev/null
fi
if [ $1 == "6" ]; then
        redshift -O 2500 >> /dev/null
fi
if [ $1 == "7" ]; then
        redshift -O 2000 >> /dev/null
fi
if [ $1 == "off" ]; then
	redshift -x >> /dev/null
fi


