#!/bin/bash
# vscodeupdate is a script that uses gdebi to unpack a new visual studio code deb package over an old one

clear
echo "Download Visual Studio Code and put it in ~/Downloads/Debs. (IMPORTANT)"
echo ""
echo Press enter when done...
read junk
clear
cd ~/Downloads/Debs
version=$(ls | grep code)
sudo gdebi $version
clear
printf "Visual Studio Code has been successfully updated to version $version\n"
