#!/bin/bash
# xssh is a script I use for sshing with the ability to use x forwarding with a shortcut to my server

pivar="192.168.0.29"
if [[ $1 == "server"]]; then
	ssh -X $2@$pivar
	exit
fi
ssh -x $2@192.168.0.$1
